apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: jaseye/udagram-reverseproxy:main
        imagePullPolicy: Always
        resources:
          requests:
             memory: "1000"
             cpu: "250m"
          limits: 
             memory: "1500Mi"
             cpu: "500m"
        ports:
        - containerPort: 80
        env:
            - name: AWS_BUCKET
              valueFrom:
               configMapKeyRef:
                 name: env-configmap
                 key: aws_bucket
            - name: AWS_REGION
              valueFrom:
               configMapKeyRef:
                 name: env-configmap
                 key: aws_region
            - name: AWS_PROFILE
              valueFrom:
               configMapKeyRef:
                 name: env-configmap
                 key: aws_profile
            - name: URL
              valueFrom:
               configMapKeyRef:
                 name: env-configmap
                 key: url 
            - name: JWT_SECRET
              valueFrom:
               secretKeyRef:
                 name: env-secret
                 key: jwt_secret
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      volumes:
           - name: aws-secret
             secret:
               secretName: aws-secret
               optional: false           
      restartPolicy: Always

            