language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "building images"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  
  - docker tag udagram-frontend jaseye/udagram-frontend:v10
  - docker tag udagram-api-feed jaseye/udagram-api-feed:main
  - docker tag udagram-api-user jaseye/udagram-api-user:main
  - docker tag udagram-reverseproxy jaseye/udagram-reverseproxy:main


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  - docker push jaseye/udagram-frontend:v10
  - docker push jaseye/udagram-api-feed:main
  - docker push jaseye/udagram-api-user:main
  - docker push jaseye/udagram-reverseproxy:main
  
