apiVersion: apps/v1
kind: Secret
metadata: 
  name: aws-secret
data: 
    credentials:
    aws_access_key_id: QUtJQTROUFlORUhMREEzVktDTVA=
    aws_secret_access_key: SGJDRDQzVi9WdCtHSWpTR0pSSHpTdEM0eUNJcUl4eGFYdUUwNEVHTQ==
type: Opaque   
   