apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jaseye/udagram-frontend:main
        ports:
        - containerPort: 80
        env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
               secretKeyRef:
                 name: aws-secret
                 key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
               secretKeyRef:
                 name: aws-secret
                 key: aws_secret_access_key
            - name: AWS_BUCKET
              valueFrom:
               configMapKeyRef:
                 name: env-configmap
                 key: aws_bucket
            - name: AWS_REGION
              valueFrom:
               configMapKeyRef:
                 name: env-configmap
                 key: aws_region
            - name: AWS_PROFILE
              valueFrom:
               configMapKeyRef:
                 name: env-configmap
                 key: aws_profile
            - name: URL
              valueFrom:
               configMapKeyRef:
                 name: env-configmap
                 key: url 
            - name: JWT_SECRET
              valueFrom:
               secretKeyRef:
                 name: env-secret
                 key: jwt_secret 
         